# Generated by Django 6.0.8 on 2026-09-29 03:16

import pessoa.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name': 'pessoa', 'verbose_name_plural': 'pessoas'},
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[pessoa.validators.validar_cpf], verbose_name='CPF'),
        ),
    ]
