# Generated by Django 6.0.2 on 2026-09-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproduto',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidoproduto',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoProduto',
        ),
    ]
