# Generated by Django 6.0.8 on 2026-09-29 03:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('pessoa', '0002_alter_pessoa_options_alter_pessoa_cpf'),
        ('produtos', '0003_alter_produto_categoria_alter_produto_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(related_name='pedidos', through='pedidos.PedidoProduto', to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoa.pessoa'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Em preparo', 'Em preparo'), ('Pronto', 'Pronto'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Novo', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='quantidade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gte', 0)), name='pedido_total_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pedidoproduto',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gte', 1)), name='item_quantidade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='pedidoproduto',
            constraint=models.CheckConstraint(condition=models.Q(('preco_unitario__gte', 0)), name='item_preco_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pedidoproduto',
            constraint=models.UniqueConstraint(fields=('pedido', 'produto'), name='item_produto_unico_por_pedido'),
        ),
    ]
